name: Test

on:
  push:
    branches:
      - "*"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test workspace
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          ls ./*
