name: deploy.yml
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          request_pty: true
          script_stop: true
          key: ${{ secrets.KEY }}
          script: |
            become copy-svg-langs sh -c "
              rm -rf ~/svg_tr_repo &&
              git clone https://github.com/Mdwiki-TD/svg_translate.git svg_tr_repo &&
              chmod -R 6770 ~/svg_tr_repo &&
              ~/svg_tr_repo/web_sh/update.sh &&
              rm -rf ~/svg_tr_repo &&
              toolforge-webservice python3.11 stop &&
              toolforge-webservice python3.11 start &&
              echo 'done..'
            "
